### ISSUE TITLE
ug, database install error

### ISSUE THREAD

**Issue by macmanes** [camillescott/dammit#55] opened 2016-03-29 19:44 UTC
using 0.2.8

```
dammit databases --install --database-dir /data/dammit_databases/
========================================
dammit! a tool for easy de novo transcriptome annotation
Camille Scott 2015
========================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
submodule: databases
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

--- Checking PATH for dependencies

          [x] HMMER

          [x] Infernal

          [x] BLAST+

          [x] BUSCO

          [x] TransDecoder

          [x] LAST

          [x] crb-blast


--- Dependency results

          All dependencies satisfied!


--- Checking for database prep (dir: /data/dammit_databases)

          [ ] download_and_gunzip:Pfam-A.hmm

          [ ] hmmpress:Pfam-A.hmm

          [ ] download_and_gunzip:Rfam.cm

          [ ] cmpress:Rfam.cm

          [ ] download_and_gunzip:aa_seq_euk.fasta

          [ ] lastdb:aa_seq_euk.fasta.db

          [ ] download_and_gunzip:ODB8_EukOGs_genes_ALL_levels.txt

          [ ] download_and_untar:dammit_databases-metazoa


--- Database results

          Database prep incomplete...


--- Installing databases

Traceback (most recent call last):
  File "/usr/local/bin/dammit", line 10, in <module>
    app.DammitApp(arg_src=sys.argv[1:]).run()
  File "/usr/local/lib/python2.7/dist-packages/dammit/app.py", line 31, in run
    self.args.func()
  File "/usr/local/lib/python2.7/dist-packages/dammit/app.py", line 189, in handle_databases
    databases.DatabaseHandler(self.args).handle()
  File "/usr/local/lib/python2.7/dist-packages/dammit/databases.py", line 66, in handle
    common.run_tasks(self.tasks, doit_args, config=self.doit_config)
  File "/usr/local/lib/python2.7/dist-packages/dammit/common.py", line 43, in run_tasks
    return DoitMain(Loader()).run(args)
  File "/usr/local/lib/python2.7/dist-packages/doit/doit_cmd.py", line 59, in __init__
    ini_config = self.load_config_ini(config_filenames)
  File "/usr/local/lib/python2.7/dist-packages/doit/doit_cmd.py", line 72, in load_config_ini
    cfg_parser = ConfigParser(allow_no_value=True, delimiters=('=',))
TypeError: __init__() got an unexpected keyword argument 'delimiters'
```

**Comment by camillescott** [comment] 2016-03-30 19:17
Oh boy. This appears to be a dupe of #33; unfortunately, the issuer stopped responding, and I never figured it out. Can you give me some details about your system -- OS version, python version -- and a listing of your Python environment? The latter can be found either with `pip list` for a virtualenv, or `conda list` for ana/miniconda.

**Comment by camillescott** [comment] 2016-03-30 21:50
Another question -- did you do the update with `--no-deps`? If so, you might want to try a full upgrade without that flag.

**Comment by camillescott** [comment] 2016-04-13 02:39
@macmanes, check #33 now -- I finally figured out how to fix this

**Closed** 2016-04-13 02:53 UTC
