### ISSUE TITLE
maf_best_hits Error

### ISSUE THREAD

**Issue by KField-Bucknell** [camillescott/dammit#52] opened 2016-03-09 10:44 UTC
dammit was installed on a fresh Ubuntu 14.04 Virtualbox running within Mac OS 10.11.
Everything worked great except for the maf_best_hits step, which generated the following error:

Some tasks failed![dammit.annotate:ERROR]
TaskError - taskid:maf_best_hits:Trinity-GG.fasta.x.orthodb.maf-Trinity-GG.fasta.x.orthodb.maf.best.csv[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dammit/tasks.py", line 304, in cmd
    df = maf.MafParser(maf_fn).read()
  File "/usr/local/lib/python2.7/dist-packages/dammit/fileio/maf.py", line 15, in read
    return pd.concat(self)
  File "/usr/local/lib/python2.7/dist-packages/pandas/tools/merge.py", line 812, in concat
    copy=copy)
  File "/usr/local/lib/python2.7/dist-packages/pandas/tools/merge.py", line 845, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
[dammit.annotate:ERROR]
Some tasks failed![dammit.annotate:ERROR]
UnmetDependency - taskid:maf-gff3:Trinity-GG.fasta.x.orthodb.maf.gff3[dammit.annotate:ERROR]
maf_best_hits:Trinity-GG.fasta.x.orthodb.maf-Trinity-GG.fasta.x.orthodb.maf.best.csv
[dammit.annotate:ERROR]
Some tasks failed![dammit.annotate:ERROR]
UnmetDependency - taskid:gff3-merge:Trinity-GG.fasta.dammit.gff3[dammit.annotate:ERROR]
maf-gff3:Trinity-GG.fasta.x.orthodb.maf.gff3
[dammit.annotate:ERROR]
Some tasks failed![dammit.annotate:ERROR]
UnmetDependency - taskid:fasta-annotate:Trinity-GG.fasta.dammit.fasta[dammit.annotate:ERROR]
gff3-merge:Trinity-GG.fasta.dammit.gff3
[dammit.annotate:ERROR]

Anyone have any idea what went wrong?

**Comment by camillescott** [comment] 2016-03-25 20:33
This is an odd one -- did the lastal step fail previously?

**Comment by lassancejm** [comment] 2016-04-13 01:22
same type of issue here with a fresh conda environment and the test data:

Some tasks failed![dammit.annotate:ERROR]
TaskError - taskid:maf_best_hits:cdna_nointrons_utrs.fa.x.orthodb.maf-cdna_nointrons_utrs.fa.x.orthodb.maf.best.csv[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/n/home01/lassance/envs/dammit/lib/python2.7/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/n/home01/lassance/envs/dammit/lib/python2.7/site-packages/dammit/tasks.py", line 304, in cmd
    df = maf.MafParser(maf_fn).read()
  File "/n/home01/lassance/envs/dammit/lib/python2.7/site-packages/dammit/fileio/maf.py", line 16, in read
    return pd.concat(self, ignore_index=True)
  File "/n/home01/lassance/envs/dammit/lib/python2.7/site-packages/pandas/tools/merge.py", line 812, in concat
    copy=copy)
  File "/n/home01/lassance/envs/dammit/lib/python2.7/site-packages/pandas/tools/merge.py", line 845, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
[dammit.annotate:ERROR]

**Comment by camillescott** [comment] 2016-04-13 01:48
It looks like `lastal` isn't finding any alignments against OrthoDB, which is causing a failure in the parsing step. This is an error I'll need to address; however, it shouldn't be happening on the test data. Can you give me some more info on your system? (OS, Python version, etc)

Also, could you run:

    python -c "import pandas; print pandas.__version__"

and

    dammit --version

Cheers,
Camille

**Comment by lassancejm** [comment] 2016-04-13 02:06
Here are the specifics; 

Python 2.7.6 |Anaconda 1.9.2 (64-bit) 

OS: CentOS 6 

pandas:
0.17.1

dammit:
dammit 0.2.9

Thanks!

JM

**Comment by camillescott** [comment] 2016-04-13 02:10
Hmm... the only thing that stands out is CentOS, which I haven't tested on. Can you attach the contents of `~/.dammit/log/dammit-all.log`?

**Comment by lassancejm** [comment] 2016-04-13 02:15
here it is

**Comment by camillescott** [comment] 2016-04-13 02:16
I think you'll have to add the attachment via the github interface, I'm not seeing anything :)

**Comment by lassancejm** [comment] 2016-04-13 02:22
ahah, apparently Github does not like the .log extension

Should work now

[dammit-all.log.txt](https://github.com/camillescott/dammit/files/216308/dammit-all.log.txt)

**Comment by camillescott** [comment] 2016-04-13 03:07
I'm honestly not even sure to begin with CentOS. Could you briefly take me through the install process you used?

**Comment by camillescott** [comment] 2016-04-13 03:07
(trying to reproduce on an EC2 instance)

**Comment by lassancejm** [comment] 2016-04-13 13:43
I followed the instructions listed here : https://portal.rc.fas.harvard.edu/apps/modules/dammit

**Comment by mddawson77** [comment] 2016-08-30 19:23
Hi Camille,

I am having the same error with my assembly and also the test data provided.  dammit v0.3, pandas v0.18.1, and python v2.7.12, and ubuntu 14.04.  The error below was from my data.  Any help would be great, thanks!

   good.transfuse_imitator_cons.fa.x.orthodb.maf.best.csv

          [ ] lastal:good.transfuse_imitator_cons.fa.x.orthodb.maf

          [ ] lastal:good.transfuse_imitator_cons.fa.x.uniref.maf

          [ ] maf_best_hits:good.transfuse_imitator_cons.fa.x.orthodb.maf-
          good.transfuse_imitator_cons.fa.x.orthodb.maf.best.csv

          [ ] maf-gff3:good.transfuse_imitator_cons.fa.x.orthodb.maf.gff3

          [ ] maf_best_hits:good.transfuse_imitator_cons.fa.x.uniref.maf-
          good.transfuse_imitator_cons.fa.x.uniref.maf.best.csv

Some tasks failed![dammit.annotate:ERROR]
TaskError - taskid:maf_best_hits:good.transfuse_imitator_cons.fa.x.uniref.maf-good.transfuse_imitator_cons.fa.x.uniref.maf.best.csv[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/site-packages/dammit/tasks.py", line 343, in cmd
    df = maf.MafParser(maf_fn).read()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/site-packages/dammit/fileio/maf.py", line 16, in read
    return pd.concat(self, ignore_index=True)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/site-packages/pandas/tools/merge.py", line 845, in concat
    copy=copy)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/site-packages/pandas/tools/merge.py", line 878, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
[dammit.annotate:ERROR]

**Comment by camillescott** [comment] 2016-10-20 22:32
Update for concerned parties: this had to do with dammit choking on empty results files. The 1.0 release which is in the oven currently takes care of this. I take it these were relatively small transcriptomes?

**Comment by camillescott** [comment] 2016-10-20 23:06
(closing this for now)

**Closed by camillescott** 2016-10-20 23:06 UTC
Labels: bug
